project_name: glab

before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - main: ./cmd/glab
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X glab.version={{.Version}} -X glab.commit={{.Commit}} -X glab.build={{time "01/02/2006"}}
  - <<: &build_defaults
      binary: bin/glab
      main: ./cmd/glab
    id: macos
    goos: [darwin]
    goarch: [amd64]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, amd64, arm64]

  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [386, amd64]

archives:
  - replacements:
      386: i386
      amd64: x86_64

  - id: nix
    builds: [macos, linux]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    replacements:
      darwin: macOS
    format: tar.gz

  - id: windows
    builds: [windows]
    <<: *archive_defaults
    wrap_in_directory: false
    format: zip

scoop:
  url_template: "http://github.com/profclems/glab/releases/{{ .Tag }}/{{ .ArtifactName }}"

  # Repository to push the app manifest to.
  bucket:
    owner: profclems
    name: glab
    # Optionally a token can be provided, if it differs from the token provided to GoReleaser
    token: "{{ .Env.SCOOP_BUCKET_GITHUB_TOKEN }}"

  commit_author:
    name: profclems
    email: clementsam75@gmail.com

  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: "https://github.com/profclems/glab"
  description: "An open source gitlab cli tool"
  license: MIT
  persist:
    - "config"
    - ".env"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
