project_name: glab

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - main: ./cmd/glab
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X glab.version={{.Version}} -X glab.commit={{.Commit}} -X glab.build={{time "01/02/2006"}}
  - <<: &build_defaults
      binary: bin/glab
    id: macos
    goos: [darwin]
    goarch: [amd64]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, amd64, arm64]

  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [386, amd64]
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
