name: Build Windows Installer

on: [push]

jobs:
  windows-installer:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
          
      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      
      - name: Install Build Tools
        run: |
          choco install innosetup make
             
      - name: Build GLab For Windows
        run: |
          make build && Rename-Item -LiteralPath "bin/glab" -NewName "bin/glab.exe" && "bin/glab.exe"
               
      - name: Create Installer
        run: |
          iscc "scripts/setup_windows.iss"
