name: Build Windows Installer

on: [push]

jobs:
  windows-installer:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
          
      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      
      - name: Install Build Tools
        run: |
          choco install innosetup make
             
      - name: Build GLab For Windows
        run: |
          make build && Get-ChildItem bin
               
      - name: Create Installer
        run: |
          echo "GLAB_CURRENT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          $srcDir = Convert-Path .
          Rename-Item -Path $srcDir/bin/glab -NewName glab.exe
          Copy-Item -Path $srcDir/scripts/setup_windows.iss -Destination $srcDir
          iscc "setup_windows.iss"

      - name: Upload Installer to Release
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.BOT_TOKEN}}
        run: gh release upload v1.12.1 ./bin/glab_1.12.1_Windows_x86_64_installer.exe --clobber
