name: goreleaser

on:
  push:
    tags:
      - "*"

jobs:
  windows-installer:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
          
      - name: Install Scoop
        run: |
          iwr -useb get.scoop.sh | iex  
  
