name: 'Issue and PR inactivity reminder'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.BOT_TOKEN }}
          stale-issue-message: "This issue has been automatically marked as stale because it has not had recent activity. We haven't had the time to address it yet, but we want to keep it open. This message is just a reminder for us to help triage issues."
          stale-pr-message: 'This PR has been automatically marked as stale because it has not had recent activity. This message is just a reminder for the author, reviewers and assignees.'
          days-before-stale: 30
          days-before-close: -1
          days-before-pr-close: -1
          exempt-issue-labels: 'waiting,never-stale,On Hold'
